import authentication from './authentication.route.js';
import credentials from './credentials.route.js';
import home from './home.route.js';
import rights from './rights.route.js';

export default {
  authentication,
  credentials,
  home,
  rights,
};

/**
 * @apiDefine Authentication Authentication
 * Authentication routes provide a token to access all known user-only routes.
 *
 * Model:
 * ```
 * "accessToken":  String,     // Unique, Autogenerated, Short-lived.
 * "refreshToken": String,     // Unique, Autogenerated, Short-lived.
 * "credential":   Credential, // Credential instance.
 * ```
 */

/**
 * @apiDefine Credentials Credentials
 * Credential routes allow the management of Credential type resources.
 *
 * Model:
 * ```
 * "id":               ObjectId, // Unique, Autogenerated.
 * "createdAt":        ISODate,  // Autogenerated.
 * "updatedAt":        ISODate,  // Autogenerated.
 * "email":            String,   // Unique.
 * "isEmailConfirmed": Boolean,  // Not required.
 * "right":            ObjectId, // Right id reference.
 * ("password":        String),  // Unselected.
 * ```
 */

/**
 * @apiDefine Home Home
 * The home route returns the general status of the API. It can be used at test dins in particular.
 *
 * Model:
 * ```
 * code:    String,
 * data:    Object,
 * message: String,
 * meta:    String,
 * status:  Number,
 * ```
 */

/**
 * @apiDefine Rights Rights
 * Right routes allow the management of Right type resources.
 *
 * Model:
 * ```
 * "id":        ObjectId, // Unique, Autogenerated.
 * "createdAt": ISODate,  // Autogenerated.
 * "updatedAt": ISODate,  // Autogenerated.
 * "level":     Number,
 * "name":      String,  // Unique.
 * ```
 */

/**
 * @apiDefine Authorization
 * @apiHeader {Token} Authorization="Bearer " Token retrieved during authentication prefixed by the discriminant 'bearer '.
 * @apiHeaderExample {json} Authorization example:
 *    {
 *        "Authorization: "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyYzFiMDZhMWVjNWNlOWM4NWNlNGE1NyIsInJpZ2h0IjoiNjJiYTQwYjI5ZjcwZDAxYjgxMzU2YjUzIiwiaWF0IjoxNjU3NTMyNzY3LCJleHAiOjE2NTc2MTkxNjd9._OelXGibz2_uvoZz_le8t6FH8jqnntEdEFz8Vwls1Ic"
 *    }
 */

/**
 * @apiDefine Permission0
 * @apiPermission Administrator (or level less than or equal to 0).
 */
